---
- name: build
  hosts: build
  become: yes

  tasks:
    - name: Ensure docker package is present
      apt:
        name: nginx
        state: present
  
    - name: Change namw
      ansible.builtin.replace:
        path: /var/www/html/index.html
        after: "Welcome nginx"
        before: "<p><script> document.write(new Date().toLocaleDateString()); </script></p>"