---
- name: build
  hosts: build
  become: yes

  tasks:

  - name: Ensure docker package is present
    apt:
      name: docker.io
      state: present

  - name: Ensure Dockerfile is present
    copy:
      src: build/Dockerfile
      dest: /tmp

  - name: Ensure Dockerfile is build
    shell: docker build /tmp

- name: run
  hosts: run
  become: yes

  tasks:

    - name: Ensure docker package is present
      apt:
        name: docker.io
        state: present

    - name: Ensure Dockerfile is present
      copy:
        src: run/Dockerfile
        state: /tmp

    - name: Ensure Dockerfile is run
      shell: docker build /tmp