---
- name: build
  hosts: build
  become: yes

  tasks:

  - name: Ensure docker package is present
    apt:
      name: docker.io
      state: present

  - name: Ensure Dockerfile is present
    copy:
      src: /build/Dockerfile
      dest: /tmp

  - name: Ensure Dockerfile is build
    command:
      name: docker build . /tmp

- name: run
  hosts: run
  become: yes

  tasks:

    - name: Ensure docker package is present
      apt:
        name: docker.io
        state: present

    - name: Ensure Dockerfile is started
      copy:
        name: /run/Dockerfile
        state: /tmp

    - name: Ensure Dockerfile is run
      command:
        name: docker build . /tmp