---
# tasks file for web
- name: install packages
  apt: 
    name: {{ item }} 
    state: present
  with_items: 
    - docker.io
    - python3-pip
    - docker
    
- name: Create a volume
  community.docker.docker_volume:
    name: volume

- name: start conteiner build
  community.docker.docker_container:
    name: build
    state: started
    image: malyshevsa/build:latest
    volumes:
      - volume:/{{ dest_folder_build }}

- name: start conteiner run
  community.docker.docker_container:
    name: run
    state: started
    image: tomcat:9.0.20-jre8-alpine
    volumes:
      - volume:{{ dest_folder_tomcat }}
    ports: 8084:8080
