---
# tasks file for web
- name: add Dockerfile
  copy: src=Dockerfile dest=/tmp

- name: install docker.io
  apt:
    name: docker.io
    state: present

- name: Create a volume
  community.docker.docker_volume:
    name: volume

- name: start conteiner build
  community.docker.docker_container:
    name: build
    image: malyshevsa/build:latest
    volumes:
      - /tmp:/war

- name: Build docker image
  community.docker.docker_image:
    build:
      path: /tmp
    name: run
    source: build

- name: start conteiner run
  community.docker.docker_container:
    name: run
    image: run:latest
    mounts:
      - target: /usr/local/tomcat/webapps/
      - source: volume
    ports: 8084:8080
