---
# tasks file for web
- name: install docker.io
  apt:
    name: docker.io
    state: present

- name: start conteiner build
  community.docker.docker_container:
    name: build
    state: present
    image: malyshevsa/build:latest
    mounts:
      - source: /tmp/war
      - target: /war

- name: start conteiner run
  community.docker.docker_container:
    name: run
    state: present
    image: tomcat:9.0.20-jre8-alpine
    mounts:
      - source: /tmp/war
      - target: /usr/local/tomcat/webapps
    ports: 8084:8080
